### ISSUE TITLE
using double quotes with char.

### ISSUE THREAD

**Issue by sasonii** [JenyaKnyazev/Tic_Tac_Toe_P_vs_P_-_P_vs_C_Imposible#1]
[line 36] return (n == 1) ? 'X' : "O";

Change it to: [line 36] return (n == 1) ? 'X' : 'O';

**Comment by JenyaKnyazev** [comment]
please try play like in the picture

[image: 273846729_4600112493449865_1552385947266975917_n.jpg]

‫בתאריך יום ב׳, 14 בפבר׳ 2022 ב-11:41 מאת ‪Sason Shmuel Lameey‬‏ <‪
***@***.***‬‏>:‬

**Comment by JenyaKnyazev** [comment]
Thenks i will fix it
