### ISSUE TITLE
problem with 

### ISSUE THREAD

**Issue by sasonii** [JenyaKnyazev/Tic_Tac_Toe_P_vs_P_-_P_vs_C_Imposible#2]
Try it. It gets into a endless loop.

**Comment by JenyaKnyazev** [comment]
I played with it right now and its work perfect try to run the exe files

**Comment by JenyaKnyazev** [comment]
The input from user need to be two just two integers without double quotes

**Comment by JenyaKnyazev** [comment]
I uploaded picture please look to see how its works

**Comment by sasonii** [comment]
משום מה זה דילג על מה שכתבתי.
כתבתי שאם אני מנסה לבחור אות אחרת בדרגת קושי 3 זה משום מה נכנס ללופ אינסופי.

**Comment by JenyaKnyazev** [comment]
אבדוק את זה עשיתי שינוי בקובץ C תנסה לקפל מחדש את קובץ C ותנסה בבקשה אני
אסדר את הבעיה יותר מאוחר

בתאריך יום ב׳, 14 בפבר׳ 2022, 19:01, מאת Sason Shmuel Lameey ‏<
***@***.***>:

**Comment by JenyaKnyazev** [comment]
אני אעדכן את כל הקבצים הבעיה שאני לא בבית עד מאוחר בלילה מקסימום מחר תראה
את השינוי סליחה על אי הנעימות

בתאריך יום ב׳, 14 בפבר׳ 2022, 19:19, מאת jenya k ***@***.***

**Comment by JenyaKnyazev** [comment]
תיקנתי ועדכנתי את כל הקבצים רק כשאתה משחק תיתן קואורדינטות כמו 1 1 ולא "1 1"

‫בתאריך יום ב׳, 14 בפבר׳ 2022 ב-19:22 מאת ‪jenya k‬‏ <‪
***@***.***‬‏>:‬

**Comment by sasonii** [comment]
תראה, לי זה לא חשוב. אל תרגיש לא בנוח או משהו כזה.
אני רק מעדכן פה כדי שתדע עבורך. בהצלחה!
